const buttons = {};

Object.assign(buttons, {
  es: {
    shop: "SHOP 🛍️",
    pokerTrips: "POKER TRIPS & VIP ✈️🏨",
    buyTickets: "BUY TICKETS 🎟️",
    giveaways: "SORTEOS 🎁",
    games: "JUEGOS 🎮",
    calendar: "CALENDARIO DE TORNEOS 📅",
    pokerBet: "POKER BET 🃏",
    news: "NOTICIAS 📰",
  },
  en: {
    shop: "SHOP 🛍️",
    pokerTrips: "POKER TRIPS & VIP ✈️🏨",
    buyTickets: "BUY TICKETS 🎟️",
    giveaways: "GIVEAWAYS 🎁",
    games: "GAMES 🎮",
    calendar: "TOURNAMENT CALENDAR 📅",
    pokerBet: "POKER BET 🃏",
    news: "NEWS 📰",
  },
  pt: {
    shop: "SHOP 🛍️",
    pokerTrips: "VIAGENS DE PÔQUER & VIP ✈️🏨",
    buyTickets: "COMPRAR INGRESSOS 🎟️",
    giveaways: "SORTEIOS 🎁",
    games: "JOGOS 🎮",
    calendar: "CALENDÁRIO DE TORNEIOS 📅",
    pokerBet: "POKER BET 🃏",
    news: "NOTÍCIAS 📰",
  },
  fr: {
    shop: "BOUTIQUE 🛍️",
    pokerTrips: "VOYAGES POKER & VIP ✈️🏨",
    buyTickets: "ACHETER DES BILLETS 🎟️",
    giveaways: "TIRAGES AU SORT 🎁",
    games: "JEUX 🎮",
    calendar: "CALENDRIER DES TOURNOIS 📅",
    pokerBet: "POKER BET 🃏",
    news: "ACTUALITÉS 📰",
  },
  de: {
    shop: "SHOP 🛍️",
    pokerTrips: "POKER-REISEN & VIP ✈️🏨",
    buyTickets: "TICKETS KAUFEN 🎟️",
    giveaways: "GEWINNSPIELE 🎁",
    games: "SPIELE 🎮",
    calendar: "TURNIERKALENDER 📅",
    pokerBet: "POKER BET 🃏",
    news: "NACHRICHTEN 📰",
  },
  it: {
    shop: "NEGOZIO 🛍️",
    pokerTrips: "VIAGGI POKER & VIP ✈️🏨",
    buyTickets: "ACQUISTA BIGLIETTI 🎟️",
    giveaways: "ESTRAZIONI 🎁",
    games: "GIOCHI 🎮",
    calendar: "CALENDARIO TORNEI 📅",
    pokerBet: "POKER BET 🃏",
    news: "NOTIZIE 📰",
  },
  ru: {
    shop: "МАГАЗИН 🛍️",
    pokerTrips: "ПОКЕР-ТУРЫ И VIP ✈️🏨",
    buyTickets: "КУПИТЬ БИЛЕТЫ 🎟️",
    giveaways: "РОЗЫГРЫШИ 🎁",
    games: "ИГРЫ 🎮",
    calendar: "КАЛЕНДАРЬ ТУРНИРОВ 📅",
    pokerBet: "POKER BET 🃏",
    news: "НОВОСТИ 📰",
  },
  ja: {
    shop: "ショップ 🛍️",
    pokerTrips: "ポーカートリップ & VIP ✈️🏨",
    buyTickets: "チケットを購入 🎟️",
    giveaways: "プレゼント企画 🎁",
    games: "ゲーム 🎮",
    calendar: "トーナメントカレンダー 📅",
    pokerBet: "POKER BET 🃏",
    news: "ニュース 📰",
  },
  zh: {
    shop: "商店 🛍️",
    pokerTrips: "撲克之旅 & VIP ✈️🏨",
    buyTickets: "購買門票 🎟️",
    giveaways: "抽獎活動 🎁",
    games: "遊戲 🎮",
    calendar: "錦標賽日曆 📅",
    pokerBet: "POKER BET 🃏",
    news: "新闻 📰",
  },
  ar: {
    shop: "المتجر 🛍️",
    pokerTrips: "رحلات البوكر وكبار الشخصيات ✈️🏨",
    buyTickets: "شراء التذاكر 🎟️",
    giveaways: "سحوبات 🎁",
    games: "ألعاب 🎮",
    calendar: "جدول البطولات 📅",
    pokerBet: "POKER BET 🃏",
    news: "أخبار 📰",
  },
  ko: {
    shop: "상점 🛍️",
    pokerTrips: "포커 여행 & VIP ✈️🏨",
    buyTickets: "티켓 구매 🎟️",
    giveaways: "이벤트 🎁",
    games: "게임 🎮",
    calendar: "토너먼트 일정 📅",
    pokerBet: "POKER BET 🃏",
    news: "뉴스 📰",
  },
  tr: {
    shop: "MAĞAZA 🛍️",
    pokerTrips: "POKER SEYAHATLERİ & VIP ✈️🏨",
    buyTickets: "BİLET SATIN AL 🎟️",
    giveaways: "ÇEKİLİŞLER 🎁",
    games: "OYUNLAR 🎮",
    calendar: "TURNUVA TAKVİMİ 📅",
    pokerBet: "POKER BET 🃏",
    news: "HABERLER 📰",
  },
  // Agregás el resto igual que hiciste antes (pl, uk, id, tl, cs, ro, sr, bs, he, vi, mn, bg...)
});

export default buttons;
